# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lin\Desktop\Pyquino\core\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1005, 634)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/usb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_splitter = QtWidgets.QSplitter(self.centralWidget)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.main_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeWidget = QtWidgets.QWidget(self.layoutWidget)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.treeWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sim_reset = QtWidgets.QPushButton(self.treeWidget)
        self.sim_reset.setObjectName("sim_reset")
        self.gridLayout.addWidget(self.sim_reset, 1, 1, 1, 1)
        self.serialmode = QtWidgets.QCheckBox(self.treeWidget)
        self.serialmode.setObjectName("serialmode")
        self.gridLayout.addWidget(self.serialmode, 2, 0, 1, 1)
        self.sim_pause = QtWidgets.QPushButton(self.treeWidget)
        self.sim_pause.setObjectName("sim_pause")
        self.gridLayout.addWidget(self.sim_pause, 0, 1, 1, 1)
        self.sim_start = QtWidgets.QPushButton(self.treeWidget)
        self.sim_start.setObjectName("sim_start")
        self.gridLayout.addWidget(self.sim_start, 0, 0, 1, 1)
        self.sim_stop = QtWidgets.QPushButton(self.treeWidget)
        self.sim_stop.setObjectName("sim_stop")
        self.gridLayout.addWidget(self.sim_stop, 1, 0, 1, 1)
        self.freemode = QtWidgets.QCheckBox(self.treeWidget)
        self.freemode.setObjectName("freemode")
        self.gridLayout.addWidget(self.freemode, 2, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Target = QtWidgets.QDoubleSpinBox(self.treeWidget)
        self.Target.setMaximum(360.0)
        self.Target.setObjectName("Target")
        self.verticalLayout.addWidget(self.Target)
        self.go = QtWidgets.QPushButton(self.treeWidget)
        self.go.setObjectName("go")
        self.verticalLayout.addWidget(self.go)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.plot = QtWidgets.QPushButton(self.treeWidget)
        self.plot.setObjectName("plot")
        self.gridLayout.addWidget(self.plot, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tree = QtWidgets.QTreeWidget(self.treeWidget)
        self.tree.setObjectName("tree")
        self.tree.header().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.tree)
        self.verticalLayout_3.addWidget(self.treeWidget)
        self.layoutWidget1 = QtWidgets.QWidget(self.main_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.painter_layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.painter_layout.setContentsMargins(0, 0, 0, 0)
        self.painter_layout.setObjectName("painter_layout")
        self.horizontalLayout.addWidget(self.main_splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1005, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuchange = QtWidgets.QMenu(self.menuFile)
        self.menuchange.setObjectName("menuchange")
        self.menuMointor = QtWidgets.QMenu(self.menuBar)
        self.menuMointor.setObjectName("menuMointor")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.openfile = QtWidgets.QAction(MainWindow)
        self.openfile.setObjectName("openfile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionVrep = QtWidgets.QAction(MainWindow)
        self.actionVrep.setObjectName("actionVrep")
        self.actionserial = QtWidgets.QAction(MainWindow)
        self.actionserial.setObjectName("actionserial")
        self.actionControl = QtWidgets.QAction(MainWindow)
        self.actionControl.setObjectName("actionControl")
        self.actionPyquino_help = QtWidgets.QAction(MainWindow)
        self.actionPyquino_help.setObjectName("actionPyquino_help")
        self.actionbasic = QtWidgets.QAction(MainWindow)
        self.actionbasic.setObjectName("actionbasic")
        self.actionmachine_human = QtWidgets.QAction(MainWindow)
        self.actionmachine_human.setObjectName("actionmachine_human")
        self.menuchange.addAction(self.actionbasic)
        self.menuchange.addAction(self.actionmachine_human)
        self.menuFile.addAction(self.openfile)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.menuchange.menuAction())
        self.menuMointor.addAction(self.actionVrep)
        self.menuMointor.addAction(self.actionserial)
        self.menuMointor.addAction(self.actionControl)
        self.menuHelp.addAction(self.actionPyquino_help)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuMointor.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyqtuino"))
        self.sim_reset.setText(_translate("MainWindow", "reset"))
        self.serialmode.setText(_translate("MainWindow", "Serial Mode"))
        self.sim_pause.setText(_translate("MainWindow", "pause"))
        self.sim_start.setText(_translate("MainWindow", "start"))
        self.sim_stop.setText(_translate("MainWindow", "stop"))
        self.freemode.setText(_translate("MainWindow", "Free Mode"))
        self.go.setText(_translate("MainWindow", "Go"))
        self.plot.setText(_translate("MainWindow", "plot"))
        self.tree.headerItem().setText(0, _translate("MainWindow", "Scene hierarchy"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuchange.setTitle(_translate("MainWindow", "change"))
        self.menuMointor.setTitle(_translate("MainWindow", "Mointor"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.openfile.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "exit"))
        self.actionVrep.setText(_translate("MainWindow", "Vrep"))
        self.actionserial.setText(_translate("MainWindow", "SerialPort"))
        self.actionControl.setText(_translate("MainWindow", "Control"))
        self.actionPyquino_help.setText(_translate("MainWindow", "Pyquino help"))
        self.actionbasic.setText(_translate("MainWindow", "basic"))
        self.actionmachine_human.setText(_translate("MainWindow", "machine human"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

