# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Lin\Desktop\Pyquino\core\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 621)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/usb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 159, 131))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(30, 159, 131))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.tab.setPalette(palette)
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 231, 361))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.comboBoxPort = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxPort.setGeometry(QtCore.QRect(90, 30, 121, 31))
        self.comboBoxPort.setObjectName("comboBoxPort")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.comboBoxBaud = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBaud.setGeometry(QtCore.QRect(90, 80, 121, 31))
        self.comboBoxBaud.setObjectName("comboBoxBaud")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.comboBoxCheckSum = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxCheckSum.setGeometry(QtCore.QRect(90, 130, 121, 31))
        self.comboBoxCheckSum.setObjectName("comboBoxCheckSum")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.comboBoxBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxBits.setGeometry(QtCore.QRect(90, 180, 121, 31))
        self.comboBoxBits.setObjectName("comboBoxBits")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.comboBoxStopBits = QtWidgets.QComboBox(self.groupBox)
        self.comboBoxStopBits.setGeometry(QtCore.QRect(90, 230, 121, 31))
        self.comboBoxStopBits.setObjectName("comboBoxStopBits")
        self.pushButtonOpenSerial = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonOpenSerial.setGeometry(QtCore.QRect(10, 280, 201, 31))
        self.pushButtonOpenSerial.setObjectName("pushButtonOpenSerial")
        self.pushButtonSendData = QtWidgets.QPushButton(self.tab)
        self.pushButtonSendData.setGeometry(QtCore.QRect(740, 210, 61, 171))
        self.pushButtonSendData.setAutoDefault(True)
        self.pushButtonSendData.setObjectName("pushButtonSendData")
        self.textEditReceived = QtWidgets.QTextEdit(self.tab)
        self.textEditReceived.setGeometry(QtCore.QRect(260, 20, 541, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditReceived.sizePolicy().hasHeightForWidth())
        self.textEditReceived.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditReceived.setFont(font)
        self.textEditReceived.setReadOnly(True)
        self.textEditReceived.setObjectName("textEditReceived")
        self.textEditSent = QtWidgets.QTextEdit(self.tab)
        self.textEditSent.setGeometry(QtCore.QRect(260, 210, 471, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEditSent.setFont(font)
        self.textEditSent.setObjectName("textEditSent")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main_splitter = QtWidgets.QSplitter(self.tab_2)
        self.main_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.main_splitter.setObjectName("main_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.main_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sim_start = QtWidgets.QPushButton(self.layoutWidget)
        self.sim_start.setObjectName("sim_start")
        self.verticalLayout_3.addWidget(self.sim_start)
        self.sim_stop = QtWidgets.QPushButton(self.layoutWidget)
        self.sim_stop.setObjectName("sim_stop")
        self.verticalLayout_3.addWidget(self.sim_stop)
        self.simtree = QtWidgets.QTreeWidget(self.layoutWidget)
        self.simtree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.simtree.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.simtree.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.simtree.setObjectName("simtree")
        self.verticalLayout_3.addWidget(self.simtree)
        self.layoutWidget1 = QtWidgets.QWidget(self.main_splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.painter_layout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.painter_layout.setContentsMargins(0, 0, 0, 0)
        self.painter_layout.setObjectName("painter_layout")
        self.verticalLayout_4.addWidget(self.main_splitter)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 10, 631, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.graphyViewModule = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.graphyViewModule.setContentsMargins(0, 0, 0, 0)
        self.graphyViewModule.setObjectName("graphyViewModule")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.graphyViewModule.addWidget(self.pushButton)
        self.treeWidget = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.treeWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tree = QtWidgets.QTreeWidget(self.treeWidget)
        self.tree.setObjectName("tree")
        self.tree.header().setSortIndicatorShown(True)
        self.verticalLayout_2.addWidget(self.tree)
        self.graphyViewModule.addWidget(self.treeWidget)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1047, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuchange = QtWidgets.QMenu(self.menuFile)
        self.menuchange.setObjectName("menuchange")
        self.menuMointor = QtWidgets.QMenu(self.menuBar)
        self.menuMointor.setObjectName("menuMointor")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionSend = QtWidgets.QAction(MainWindow)
        self.actionSend.setObjectName("actionSend")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionVrep = QtWidgets.QAction(MainWindow)
        self.actionVrep.setObjectName("actionVrep")
        self.actionserial = QtWidgets.QAction(MainWindow)
        self.actionserial.setObjectName("actionserial")
        self.actionControl = QtWidgets.QAction(MainWindow)
        self.actionControl.setObjectName("actionControl")
        self.actionPyquino_help = QtWidgets.QAction(MainWindow)
        self.actionPyquino_help.setObjectName("actionPyquino_help")
        self.actionbasic = QtWidgets.QAction(MainWindow)
        self.actionbasic.setObjectName("actionbasic")
        self.actionmachine_human = QtWidgets.QAction(MainWindow)
        self.actionmachine_human.setObjectName("actionmachine_human")
        self.menuchange.addAction(self.actionbasic)
        self.menuchange.addAction(self.actionmachine_human)
        self.menuFile.addAction(self.actionSend)
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addAction(self.menuchange.menuAction())
        self.menuMointor.addAction(self.actionVrep)
        self.menuMointor.addAction(self.actionserial)
        self.menuMointor.addAction(self.actionControl)
        self.menuHelp.addAction(self.actionPyquino_help)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuMointor.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyqtuino"))
        self.groupBox.setTitle(_translate("MainWindow", "com setting"))
        self.label_2.setText(_translate("MainWindow", "com"))
        self.label.setText(_translate("MainWindow", "baurd"))
        self.label_3.setText(_translate("MainWindow", "first"))
        self.label_4.setText(_translate("MainWindow", "data"))
        self.label_5.setText(_translate("MainWindow", "stop"))
        self.pushButtonOpenSerial.setText(_translate("MainWindow", "open"))
        self.pushButtonSendData.setText(_translate("MainWindow", "send"))
        self.textEditSent.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Com"))
        self.sim_start.setText(_translate("MainWindow", "start"))
        self.sim_stop.setText(_translate("MainWindow", "stop"))
        self.simtree.headerItem().setText(0, _translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Control"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tree.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.tree.headerItem().setText(1, _translate("MainWindow", "compoment"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "custom"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuchange.setTitle(_translate("MainWindow", "change"))
        self.menuMointor.setTitle(_translate("MainWindow", "Mointor"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSend.setText(_translate("MainWindow", "send Gcode"))
        self.actionExit.setText(_translate("MainWindow", "exit"))
        self.actionVrep.setText(_translate("MainWindow", "Vrep"))
        self.actionserial.setText(_translate("MainWindow", "SerialPort"))
        self.actionControl.setText(_translate("MainWindow", "Control"))
        self.actionPyquino_help.setText(_translate("MainWindow", "Pyquino help"))
        self.actionbasic.setText(_translate("MainWindow", "basic"))
        self.actionmachine_human.setText(_translate("MainWindow", "machine human"))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

